/*
    Product data for Stage 6.
    Each product name, category, price, image, and description is stored here.
    script.js reads this list to create product cards and the shopping cart.
*/

const products = [
    {
        "id": "gc-001",
        "name": "CELLECT - Beauty Beam Rejuvenating Red",
        "brand": "CELLECT",
        "category": "Tools",
        "price": 6440,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Cellect-Rejuvenating-Red.jpg?v=1756220213",
        "description": "A practical beauty tool for at-home routines. It helps customers make their skincare steps easier and more consistent.",
        "details": "This product is selected for customers who want a more practical routine at home. It can be explained as a tool category item in our beauty store catalogue. Brand: CELLECT. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-002",
        "name": "MAKE P:REM - Safe me. Relief Essence Toner",
        "brand": "MAKE P:REM",
        "category": "Toners & Essences",
        "price": 1050,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Make-Prem-Relief-Essence-Toner.jpg?v=1752910739",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: MAKE P:REM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-003",
        "name": "DR ALTHEA - 345 Relief Cream",
        "brand": "DR ALTHEA",
        "category": "Moisturizers",
        "price": 945,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Revamped-Dr-Althea-Revamped-345-Relief-Cream-01.png?v=1715304073",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: DR ALTHEA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-004",
        "name": "Soko Glam - Summer Glow Set",
        "brand": "Soko Glam",
        "category": "Sun Care",
        "price": 2100,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/SokoGlamPDP_SummerSet_1.png?v=1777931542",
        "description": "A daily sun care option for morning routines. It supports protection while keeping the skincare routine simple.",
        "details": "This product belongs to the daytime routine. It is important because sun care is a common daily skincare need. Brand: Soko Glam. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-005",
        "name": "Soko Glam - Glow On The Go Kit",
        "brand": "Soko Glam",
        "category": "Sets",
        "price": 1575,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/GlowontheGoKit.png?v=1777074849",
        "description": "A curated set that brings several beauty steps together. It is useful for gifting or trying a complete routine.",
        "details": "This product is useful because it combines more than one routine step. Sets also make the store look more realistic and gift-friendly. Brand: Soko Glam. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-006",
        "name": "Soko Glam - Exclusive Skin Flooding Kit",
        "brand": "Soko Glam",
        "category": "Cleansers",
        "price": 3500,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/SokoGlamPDP_SkinFloodingSetUpdate_1.png?v=1775591049",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: Soko Glam. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-007",
        "name": "WANDER BEAUTY - Baggage Claim Deluxe Eye Mask Set - Limited Edition",
        "brand": "WANDER BEAUTY",
        "category": "Masks",
        "price": 1330,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Wander-Baggage-Claim-Deluxe-Eye-Masks-01.png?v=1731000245",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: WANDER BEAUTY. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-008",
        "name": "Anillo - Amber528 Parfum Body Mist",
        "brand": "Anillo",
        "category": "Body & Hair",
        "price": 1096,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Anillo-Amber528-Parfum-Body-Mist.jpg?v=1756221082",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: Anillo. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-009",
        "name": "Anillo - Rosy Night Set",
        "brand": "Anillo",
        "category": "Toners & Essences",
        "price": 1813,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Anillo_Rosy_Night_Set.jpg?v=1756221926",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: Anillo. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-010",
        "name": "DEWYTREE - Hi Amino All Cleansing Milk",
        "brand": "DEWYTREE",
        "category": "Cleansers",
        "price": 554,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/DewyTree-Hi-Amino-Cleansing-Milk.jpg?v=1756218763",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: DEWYTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-011",
        "name": "UNLEASHIA - Glitterpedia Eye Palette - No1. All of Glitter",
        "brand": "UNLEASHIA",
        "category": "K-Beauty",
        "price": 612,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Unleashia-Glitterpedia-No-1-All-Of-Glitter.jpg?v=1756218934",
        "description": "A Korean beauty product selected for modern routines. It adds variety and trend-focused care to the catalogue.",
        "details": "This product represents the K-beauty theme of the project. It adds variety and makes the catalogue more professional. Brand: UNLEASHIA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-012",
        "name": "Torriden - Balanceful Cica Cleansing Gel",
        "brand": "Torriden",
        "category": "Cleansers",
        "price": 770,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Torriden-Balanceful-Cleansing-Gel.jpg?v=1756218937",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: Torriden. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-013",
        "name": "The Lab By Blanc Doux - Oligo Hyaluronic Acid Deep Toner",
        "brand": "The Lab By Blanc Doux",
        "category": "Toners & Essences",
        "price": 770,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/The-Lab-By-Blanc-Doux-Oligo-Hyaluronic-Acid-Deep-Toner.jpg?v=1756221101",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: The Lab By Blanc Doux. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-014",
        "name": "The Lab By Blanc Doux - Green Flavonoid 2.5 Solution",
        "brand": "The Lab By Blanc Doux",
        "category": "Toners & Essences",
        "price": 735,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/The-Lab-By-Blanc-Doux-Green-Flavonoid-Solution.jpg?v=1756219992",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: The Lab By Blanc Doux. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-015",
        "name": "The Lab By Blanc Doux - Green Flavonoid 2.5 Pads",
        "brand": "The Lab By Blanc Doux",
        "category": "Toners & Essences",
        "price": 770,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/The-Lab-By-Blanc-Doux-Green-Flavonoid-2.5-Pad_1.jpg?v=1756941814",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: The Lab By Blanc Doux. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-016",
        "name": "The Lab By Blanc Doux - Oligo Hyaluronic Acid Hydro Serum",
        "brand": "The Lab By Blanc Doux",
        "category": "Serums",
        "price": 945,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/The-Lab-By-Blanc-Doux-Oligo-Hyaluronic-Acid-Hydro-Serum.jpg?v=1752910750",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: The Lab By Blanc Doux. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-017",
        "name": "SOME BY MI - Galactomyces Pure Vitamin C Glow Toner",
        "brand": "SOME BY MI",
        "category": "Toners & Essences",
        "price": 785,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/SOMEBYMI_GALACTOMYCES-PURE-VITAMIN-C-GLOW-TONER.jpg?v=1756219054",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: SOME BY MI. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-018",
        "name": "SIORIS - My First Essener",
        "brand": "SIORIS",
        "category": "Toners & Essences",
        "price": 1120,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/products/10.1-Soko-Glam-PDP-Sioris-My-First-Essener-Korean-Skincare.jpg?v=1633358390",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: SIORIS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-019",
        "name": "Plodica - Always Youth Cream",
        "brand": "Plodica",
        "category": "Moisturizers",
        "price": 1155,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Plodica-Always-Youth-Cream.jpg?v=1756941803",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: Plodica. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-020",
        "name": "Plodica - Youth Up Ampoule",
        "brand": "Plodica",
        "category": "Serums",
        "price": 1120,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Plodica-Youth-Up-Ampoule-01.png?v=1690228671",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: Plodica. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-021",
        "name": "NEOGEN - Dermalogy Extra Clear Eye Remover",
        "brand": "NEOGEN",
        "category": "K-Beauty",
        "price": 665,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Neogen-Extra-Clear-Eye-Remover-01.png?v=1706720198",
        "description": "A Korean beauty product selected for modern routines. It adds variety and trend-focused care to the catalogue.",
        "details": "This product represents the K-beauty theme of the project. It adds variety and makes the catalogue more professional. Brand: NEOGEN. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-022",
        "name": "MIXSOON - Centella Mask Pack (5 Pack)",
        "brand": "MIXSOON",
        "category": "Masks",
        "price": 700,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Mixsoon-Centella-Mask-Pack.jpg?v=1756220671",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: MIXSOON. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-023",
        "name": "MIXSOON - Soondy Centella Asiatica Essence",
        "brand": "MIXSOON",
        "category": "Toners & Essences",
        "price": 784,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Mixsoon-Soondy-Centella-Asiatica-Essence.jpg?v=1756219465",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: MIXSOON. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-024",
        "name": "MIXSOON - Master Gentle Recipe Foam Cleanser",
        "brand": "MIXSOON",
        "category": "Cleansers",
        "price": 805,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Mixsoon-Master-Gentle-Recipe-Foam-Cleanser_1.jpg?v=1756911440",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: MIXSOON. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-025",
        "name": "MEDIHEAL - THE N.M.F Ampoule Mask 10 Pack",
        "brand": "MEDIHEAL",
        "category": "Serums",
        "price": 1050,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Mediheal-The-N.M.F-Ampoule-Mask_1.jpg?v=1684272937",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: MEDIHEAL. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-026",
        "name": "MEDIHEAL - Theraffin Hand Mask",
        "brand": "MEDIHEAL",
        "category": "Masks",
        "price": 61,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/products/3.3-Soko-Glam-PDP-Mediheal-Theraffin-Hand-Mask.jpg?v=1636559404",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: MEDIHEAL. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-027",
        "name": "MEDIHEAL - N.M.F Intensive Hydrating Cream",
        "brand": "MEDIHEAL",
        "category": "Moisturizers",
        "price": 525,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/products/3.4-Soko-Glam-PDP-Mediheal-N.M.F-Intensive-Hydrating-Cream-Package.jpg?v=1636559396",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: MEDIHEAL. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-028",
        "name": "MAKE P:REM - Safe Me. Relief Moisture Cream 12",
        "brand": "MAKE P:REM",
        "category": "Moisturizers",
        "price": 1260,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/MakePrem_SafeMe.ReliefMoistureCream12_PackageUpdate.jpg?v=1756221601",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: MAKE P:REM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-029",
        "name": "MAKE P:REM - Safe me. Amino Refresh Cleansing Balm",
        "brand": "MAKE P:REM",
        "category": "Cleansers",
        "price": 945,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Make-Prem-Amino-Refresh-Cleansing-Balm.jpg?v=1756219253",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: MAKE P:REM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-030",
        "name": "LAPCOS - Chaga Rest Essence Toner",
        "brand": "LAPCOS",
        "category": "Toners & Essences",
        "price": 1120,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Lapcos-Chaga-Rest-Essence-Toner.jpg?v=1756218655",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: LAPCOS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-031",
        "name": "LA'DOR - Tea Tree Scalp Clinic Hair Pack",
        "brand": "LA'DOR",
        "category": "Serums",
        "price": 665,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/LadorTeaTreeScalpClinicHairPack.jpg?v=1756221170",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: LA'DOR. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-032",
        "name": "KLAIRS - Fundamental Water Gel Cream",
        "brand": "KLAIRS",
        "category": "Moisturizers",
        "price": 1085,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Klairs-Fundamental-Water-Gel-Cream.jpg?v=1756221907",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: KLAIRS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-033",
        "name": "ISNTREE - Hyaluronic Acid Toner Plus",
        "brand": "ISNTREE",
        "category": "Toners & Essences",
        "price": 844,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/HA_toner_plus_200ml.jpg?v=1756219434",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: ISNTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-034",
        "name": "INWARD - YULMU  Brightening Spot Cream",
        "brand": "INWARD",
        "category": "Moisturizers",
        "price": 1085,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Inward-YULMU-Brightening-Spot-Cream.jpg?v=1756218860",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: INWARD. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-035",
        "name": "I'M FROM - Body Wash - Nyeok",
        "brand": "I'M FROM",
        "category": "Body & Hair",
        "price": 1190,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-I_m-from-Body-Wash-Nyeok-01.png?v=1698612304",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: I'M FROM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-036",
        "name": "I'M FROM - Mushroom Collagen Cream",
        "brand": "I'M FROM",
        "category": "Moisturizers",
        "price": 1225,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/I_m-From-Mushroom-Collagen-Cream.jpg?v=1756220552",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: I'M FROM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-037",
        "name": "Hero Cosmetics - Mighty Patch - Micropoint",
        "brand": "Hero Cosmetics",
        "category": "Serums",
        "price": 455,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko_Glam_Revamped_PDP_Hero_Cosmetic_Mighty_Patch_Micropoint_for_Blemishes.png?v=1686200404",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: Hero Cosmetics. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-038",
        "name": "GLOWIEST - Effortless Glow Lip Oil",
        "brand": "GLOWIEST",
        "category": "Serums",
        "price": 840,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/GlowiestLipOilEffortlessGlowLipOilgroup.jpg?v=1758827665",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: GLOWIEST. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-039",
        "name": "ETUDE - Glow Fixing Tint",
        "brand": "ETUDE",
        "category": "Moisturizers",
        "price": 370,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Etude-Glow-Fixing-Tint-01.png?v=1708632505",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: ETUDE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-040",
        "name": "ERBORIAN - BB Creme Au Ginseng",
        "brand": "ERBORIAN",
        "category": "Moisturizers",
        "price": 1610,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/products/Erborian_BB_Creme_Au_Ginseng_Caramel_PDP_1.jpg?v=1678733608",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: ERBORIAN. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-041",
        "name": "Dr. Orga - pH-balanced Houttuynia Cordata Body Wash",
        "brand": "Dr. Orga",
        "category": "Body & Hair",
        "price": 671,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr-Orga-Houttuynia-Cordata-Body-Wash.jpg?v=1756219836",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: Dr. Orga. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-042",
        "name": "Dr. Orga - Alpine Rose Conditioner",
        "brand": "Dr. Orga",
        "category": "Serums",
        "price": 729,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr-Orga-Alpine-Rose-Conditioner.jpg?v=1753653170",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: Dr. Orga. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-043",
        "name": "Dr. Orga - Alpine Rose Shampoo",
        "brand": "Dr. Orga",
        "category": "Body & Hair",
        "price": 671,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr-Orga-Alpine-Rose-Shampoo.jpg?v=1756220469",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: Dr. Orga. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-044",
        "name": "Dr. Orga - Rosemary & Mint Shampoo",
        "brand": "Dr. Orga",
        "category": "Body & Hair",
        "price": 671,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr-Orga-Rosemary-mint-Shampoo.jpg?v=1756220267",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: Dr. Orga. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-045",
        "name": "Dr. Orga - Pure Tamanu Light Oil",
        "brand": "Dr. Orga",
        "category": "Body & Hair",
        "price": 963,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr-Orga-Pure-Tamanu-Light-Oil.jpg?v=1756220747",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: Dr. Orga. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-046",
        "name": "DR ORACLE - Cornflower Blue Ampoule",
        "brand": "DR ORACLE",
        "category": "Serums",
        "price": 700,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr-Oracle-Cornflower-Blue-Ampoule.jpg?v=1756220020",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: DR ORACLE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-047",
        "name": "DR ALTHEA - Oasis Soothing Mask",
        "brand": "DR ALTHEA",
        "category": "Masks",
        "price": 441,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr.Althea-Oasis-Soothing-Mask.jpg?v=1756220320",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: DR ALTHEA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-048",
        "name": "DR ALTHEA - Dr. Althea Herb Therapy Velvet Mask (10 pack)",
        "brand": "DR ALTHEA",
        "category": "Masks",
        "price": 928,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr.-Althea-Herb-Therapy-Velvet-Mask-10-pack.jpg?v=1756219456",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: DR ALTHEA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-049",
        "name": "DR ALTHEA - Essential Skin Conditioner Silk Mask (5 pack)",
        "brand": "DR ALTHEA",
        "category": "Masks",
        "price": 529,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/products/Soko-Glam-Dr.-Althea-Essential-Skin-Conditioner-Silk-Mask-_5-pack_-PDP.jpg?v=1636559419",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: DR ALTHEA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-050",
        "name": "DR ALTHEA - Rapid Firm Sculpting Cream",
        "brand": "DR ALTHEA",
        "category": "Moisturizers",
        "price": 1260,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr.-Althea-Rapid-Firm-Sculpting-Cream.jpg?v=1756221575",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: DR ALTHEA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-051",
        "name": "DR ALTHEA - Amino Acid Gentle Bubble Cleanser",
        "brand": "DR ALTHEA",
        "category": "Cleansers",
        "price": 630,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr-Althea-Amino-Acid-Gentle-Bubble-Cleanser.jpg?v=1756220943",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: DR ALTHEA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-052",
        "name": "DEWYTREE - Ultra Vitalizing Snail Cream",
        "brand": "DEWYTREE",
        "category": "Moisturizers",
        "price": 1505,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dewytree-Ultra-Vitalizing-Snail-Cream-Skin-Care-Korean.jpg?v=1756218940",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: DEWYTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-053",
        "name": "DEWYTREE - Cica 100 Essence",
        "brand": "DEWYTREE",
        "category": "Toners & Essences",
        "price": 1085,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dewytree-Cica-100-Essence.jpg?v=1756220939",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: DEWYTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-054",
        "name": "DEWYTREE - Ultra Vitalizing Snail Serum",
        "brand": "DEWYTREE",
        "category": "Serums",
        "price": 1505,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/products/8.5-Soko-Glam-PDP-_Renewal_-Dewytree-Ultra-Vitalizing-Snail-Serum-Korean-Skincare.jpg?v=1637097115",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: DEWYTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-055",
        "name": "DEWYTREE - Hi Amino All Cleanser",
        "brand": "DEWYTREE",
        "category": "Cleansers",
        "price": 560,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dewytree-Hi-Amino-All-Cleanser.jpg?v=1756220165",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: DEWYTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-056",
        "name": "BENTON - Goodbye Redness Centella Mask Pack",
        "brand": "BENTON",
        "category": "Masks",
        "price": 980,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/products/Soko-Glam-PDP-Image-Goodbye-Redness-Centella-Mask-Pack-Single.jpg?v=1677478547",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: BENTON. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-057",
        "name": "SOKO GLAM - Family Body Care Set",
        "brand": "SOKO GLAM",
        "category": "Sets",
        "price": 861,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Revamped-DermaB-Body-Care-Set-01.png?v=1715185845",
        "description": "A curated set that brings several beauty steps together. It is useful for gifting or trying a complete routine.",
        "details": "This product is useful because it combines more than one routine step. Sets also make the store look more realistic and gift-friendly. Brand: SOKO GLAM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-058",
        "name": "Aestura - A-Cica Blemish Relief Serum",
        "brand": "Aestura",
        "category": "Serums",
        "price": 1365,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Aestura-A-Cica-365-Blemish-Relief-Serum-01.png?v=1715981504",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: Aestura. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-059",
        "name": "ACWELL - pH Balancing Watery Cleansing Oil",
        "brand": "ACWELL",
        "category": "Cleansers",
        "price": 875,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Acwell-Revamped-pH-Balancing-Watery-Cleansing-Oil.jpg?v=1756221494",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: ACWELL. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-060",
        "name": "NEOGEN - Dermalogy Extra Volumecurl Metal Maxicara - Black",
        "brand": "NEOGEN",
        "category": "K-Beauty",
        "price": 1330,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Neogen-Dermalogy-Extra-Volume-Curl-Metal-Maxicara-01_2.png?v=1697493798",
        "description": "A Korean beauty product selected for modern routines. It adds variety and trend-focused care to the catalogue.",
        "details": "This product represents the K-beauty theme of the project. It adds variety and makes the catalogue more professional. Brand: NEOGEN. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-061",
        "name": "SON & PARK - Beauty Water",
        "brand": "SON & PARK",
        "category": "Cleansers",
        "price": 1050,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Son_ParkBeautyWater.jpg?v=1757373158",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: SON & PARK. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-062",
        "name": "Knours - Your Only Meditation Gel Cream",
        "brand": "Knours",
        "category": "Moisturizers",
        "price": 840,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Knours-Your-Only-Meditation-Gel-Cream-01_1.png?v=1756220985",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: Knours. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-063",
        "name": "HUXLEY - Body Lotion - Moroccan Gardener",
        "brand": "HUXLEY",
        "category": "Body & Hair",
        "price": 1260,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Huxely-BODY-LOTION-MOROCCAN-GARDENER.jpg?v=1753399900",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: HUXLEY. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-064",
        "name": "TONY MOLY - Timeless Ferment Snail Lip Treatment Stick",
        "brand": "TONY MOLY",
        "category": "Serums",
        "price": 385,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Tony-Moly-Timeless-Ferment-Snail-Lip-Treatment-Stick.jpg?v=1756219225",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: TONY MOLY. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-065",
        "name": "ISNTREE - Mugwort Calming Clay Mask",
        "brand": "ISNTREE",
        "category": "Masks",
        "price": 840,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Isentree_Mugwort_calming_clay_mask_100ml.jpg?v=1756221412",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: ISNTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-066",
        "name": "ISNTREE - Green Tea Fresh Serum",
        "brand": "ISNTREE",
        "category": "Serums",
        "price": 1096,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Isntree-Green-Tea-Fresh-Serum.jpg?v=1756221217",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: ISNTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-067",
        "name": "ISNTREE - Chestnut 8% AHA Clear Essence",
        "brand": "ISNTREE",
        "category": "Toners & Essences",
        "price": 634,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Isentree_CHESTNUT_AHA_8__CLEAR_ESSENCE.jpg?v=1756220993",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: ISNTREE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-068",
        "name": "ELOREA - HEAVEN (건) Eau De Parfum (10ml)",
        "brand": "ELOREA",
        "category": "K-Beauty",
        "price": 1750,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Elorea-Heaven-04_1_29fefcef-57bf-4e0f-ad02-ac2244e03c58.png?v=1729809618",
        "description": "A Korean beauty product selected for modern routines. It adds variety and trend-focused care to the catalogue.",
        "details": "This product represents the K-beauty theme of the project. It adds variety and makes the catalogue more professional. Brand: ELOREA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-069",
        "name": "SOKO GLAM - Soko Glam Logo Baseball Cap",
        "brand": "SOKO GLAM",
        "category": "K-Beauty",
        "price": 700,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/SokoGlamBrandedBaseballCap-A.jpg?v=1756218670",
        "description": "A Korean beauty product selected for modern routines. It adds variety and trend-focused care to the catalogue.",
        "details": "This product represents the K-beauty theme of the project. It adds variety and makes the catalogue more professional. Brand: SOKO GLAM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-070",
        "name": "IOPE - XMD Stem III Clinical Recovery Serum",
        "brand": "IOPE",
        "category": "Serums",
        "price": 2870,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Iope-XMD-Serum-01.png?v=1768420123",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: IOPE. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-071",
        "name": "SIORIS - Cleanse Me Softly Milk Cleanser",
        "brand": "SIORIS",
        "category": "Cleansers",
        "price": 980,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Sioris-Cleanse-Me-Softly-Milk-Cleanser.jpg?v=1756219683",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: SIORIS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-072",
        "name": "NEOGEN - Day-Light Protection Airy Sunscreen",
        "brand": "NEOGEN",
        "category": "Sun Care",
        "price": 1120,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/New-Curation-Neogen-DAY-LIGHT-PROTECTION-AIRYSUNSCREEN_1.jpg?v=1754962658",
        "description": "A daily sun care option for morning routines. It supports protection while keeping the skincare routine simple.",
        "details": "This product belongs to the daytime routine. It is important because sun care is a common daily skincare need. Brand: NEOGEN. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-073",
        "name": "DR ALTHEA - 147 Barrier Cream",
        "brand": "DR ALTHEA",
        "category": "Moisturizers",
        "price": 945,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Dr.Althea_147BarrierCream.jpg?v=1756218704",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: DR ALTHEA. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-074",
        "name": "VT COSMETICS - VT Reedle Shot 300",
        "brand": "VT COSMETICS",
        "category": "Serums",
        "price": 1050,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/1_Resized_345de61a-1687-459a-ba72-c51c700f4244.jpg?v=1768947329",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-075",
        "name": "Purito Seoul - Oat-in Calming Gel Cream",
        "brand": "Purito Seoul",
        "category": "Moisturizers",
        "price": 683,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/GB_OatinCalminggelCream_nobg_Resized_25812624-dc2a-4ed9-943b-87673c969e4b.jpg?v=1768606700",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: Purito Seoul. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-076",
        "name": "Purito Seoul - Oat-in Gentle Exfoliating Face Cleanser",
        "brand": "Purito Seoul",
        "category": "Cleansers",
        "price": 770,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/OatCleanser_nobg_Resized_63e51175-dead-4a24-a26d-eab52f43b287.jpg?v=1768414379",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: Purito Seoul. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-077",
        "name": "Then I Met You - Snail Mucin Eye Cream",
        "brand": "Then I Met You",
        "category": "Moisturizers",
        "price": 1610,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/850009701312-hero_f7b2d586-d3ad-4683-b4f9-93d6d34ec4b3.jpg?v=1767989544",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: Then I Met You. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-078",
        "name": "Cell Fusion C - Airy Stick Sunscreen",
        "brand": "Cell Fusion C",
        "category": "Sun Care",
        "price": 805,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Cell-Fusion-C-AiryStickSunscreen-01.png?v=1767754983",
        "description": "A daily sun care option for morning routines. It supports protection while keeping the skincare routine simple.",
        "details": "This product belongs to the daytime routine. It is important because sun care is a common daily skincare need. Brand: Cell Fusion C. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-079",
        "name": "MELIXIR - Melixir Mandarin Vitamin CE Hydration Cream",
        "brand": "MELIXIR",
        "category": "Moisturizers",
        "price": 945,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Melixir-Mandarin-Vitamin-CE-Hydration-Cream.png?v=1760384529",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: MELIXIR. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-080",
        "name": "MELIXIR - Melixir Mandarin Morning Face Cleanser",
        "brand": "MELIXIR",
        "category": "Cleansers",
        "price": 875,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Melixir-Mandarin-Morning-Face-Cleanser.png?v=1760384521",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: MELIXIR. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-081",
        "name": "SOKO GLAM - 10-Step Korean Skin Care Routine Set (Dry Skin Type)",
        "brand": "SOKO GLAM",
        "category": "Sets",
        "price": 6965,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/10-StepKoreanSkinCareRoutineSet_DrySkinType.png?v=1773098613",
        "description": "A curated set that brings several beauty steps together. It is useful for gifting or trying a complete routine.",
        "details": "This product is useful because it combines more than one routine step. Sets also make the store look more realistic and gift-friendly. Brand: SOKO GLAM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-082",
        "name": "SOKO GLAM - 10-Step Korean Skin Care Routine Set (Normal Skin Type)",
        "brand": "SOKO GLAM",
        "category": "Sets",
        "price": 7210,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Soko-Glam-10-Step-Korean-Skin-Care-Routine-Set-Normal-Skin-Type_1_21eedc34-e6ca-425f-8a76-6b3c4f1839d2_1.png?v=1767818106",
        "description": "A curated set that brings several beauty steps together. It is useful for gifting or trying a complete routine.",
        "details": "This product is useful because it combines more than one routine step. Sets also make the store look more realistic and gift-friendly. Brand: SOKO GLAM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-083",
        "name": "NATURIUM - Dew-Glow Tinted Moisturizer SPF 50+",
        "brand": "NATURIUM",
        "category": "Moisturizers",
        "price": 805,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/dewglowtinteddeep1_Resized.jpg?v=1763179496",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-084",
        "name": "NATURIUM - The Perfector Salicylic Acid Body Wash",
        "brand": "NATURIUM",
        "category": "Cleansers",
        "price": 595,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/NATR-40005_The-Perfector_Generic_front_Resized.jpg?v=1761427456",
        "description": "A cleanser for the first step of the routine. It helps remove daily buildup and prepares the skin for care products.",
        "details": "This product is the starting point of a routine. Cleansers are included so the catalogue is not only makeup, but also skincare focused. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-085",
        "name": "NATURIUM - Multi-Peptide Advanced Serum",
        "brand": "NATURIUM",
        "category": "Serums",
        "price": 875,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/NATR-10102-Multi-Peptide-Advanced-Serum-01_Resized.jpg?v=1761628455",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-086",
        "name": "NATURIUM - Phyto-Glow Lip Balm SPF 45",
        "brand": "NATURIUM",
        "category": "Serums",
        "price": 438,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Naturium-Resized-6.png?v=1763678811",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-087",
        "name": "NATURIUM - The Glow Getter Multi-Oil Body Butter",
        "brand": "NATURIUM",
        "category": "Body & Hair",
        "price": 700,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Naturium-Resized-4.png?v=1763678829",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-088",
        "name": "NATURIUM - The Glow Getter Body Oil",
        "brand": "NATURIUM",
        "category": "Body & Hair",
        "price": 840,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Naturium-Resized-3.png?v=1763678796",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-089",
        "name": "NATURIUM - Urea 5% Body Serum",
        "brand": "NATURIUM",
        "category": "Serums",
        "price": 770,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Naturium-Resized-1.png?v=1763678800",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-090",
        "name": "NATURIUM - The Energizer Mandelic Acid Body Wash",
        "brand": "NATURIUM",
        "category": "Body & Hair",
        "price": 595,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Naturium-Resized.png?v=1763678786",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-091",
        "name": "NATURIUM - The Calmer Ceramide Body Wash",
        "brand": "NATURIUM",
        "category": "Body & Hair",
        "price": 595,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Naturium-Resized-2.png?v=1763678832",
        "description": "A body and hair care item for everyday self-care. It supports softness, freshness, and a more complete beauty routine.",
        "details": "This product expands the store beyond face products. It helps Glow Cosmetics feel like a complete beauty shop. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-092",
        "name": "NATURIUM - Multi-Peptide Rich Cream",
        "brand": "NATURIUM",
        "category": "Moisturizers",
        "price": 875,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Naturium-Resized-7.png?v=1764710805",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-093",
        "name": "NATURIUM - Barrier Bounce Serum",
        "brand": "NATURIUM",
        "category": "Serums",
        "price": 840,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-Naturium-Resized-5.png?v=1763678783",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: NATURIUM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-094",
        "name": "VT COSMETICS - VT Reedle Shot Starter Kit (8ct)",
        "brand": "VT COSMETICS",
        "category": "Sets",
        "price": 350,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-VTReedleResized-5.png?v=1763678839",
        "description": "A curated set that brings several beauty steps together. It is useful for gifting or trying a complete routine.",
        "details": "This product is useful because it combines more than one routine step. Sets also make the store look more realistic and gift-friendly. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-095",
        "name": "VT COSMETICS - VT Color Reedle Shot Starter Stick Kit (8ct)",
        "brand": "VT COSMETICS",
        "category": "Sets",
        "price": 350,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-VTReedleResized-1_e0ebdf12-d724-48d2-a59d-79963184a9da.png?v=1763678803",
        "description": "A curated set that brings several beauty steps together. It is useful for gifting or trying a complete routine.",
        "details": "This product is useful because it combines more than one routine step. Sets also make the store look more realistic and gift-friendly. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-096",
        "name": "VT COSMETICS - VT PDRN Cream 100",
        "brand": "VT COSMETICS",
        "category": "Moisturizers",
        "price": 910,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-VTReedleResized-2.png?v=1763678792",
        "description": "A moisturizing product that helps the skin feel soft, balanced, and comfortable after the previous skincare steps.",
        "details": "This product completes the routine by adding comfort and hydration. It is one of the core categories in a skincare store. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-097",
        "name": "VT COSMETICS - VT PDRN Essence 100",
        "brand": "VT COSMETICS",
        "category": "Toners & Essences",
        "price": 980,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-VTReedleResized-3.png?v=1763678789",
        "description": "A lightweight toner or essence step for daily hydration. It prepares the skin before serum and moisturizer.",
        "details": "This product belongs to the preparation step of skincare. It is used after cleansing and before stronger treatment products. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-098",
        "name": "VT COSMETICS - VT Reedle Shot 100",
        "brand": "VT COSMETICS",
        "category": "Serums",
        "price": 910,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-VTReedleResized-4.png?v=1763678779",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-099",
        "name": "VT COSMETICS - VT Reedle Shot 50",
        "brand": "VT COSMETICS",
        "category": "Serums",
        "price": 700,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-VTReedleResized-7_2c8c181b-d69a-4a3a-8bc0-d7e5743fda43.png?v=1763678825",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-100",
        "name": "VT COSMETICS - VT Collagen Reedle Shot 100",
        "brand": "VT COSMETICS",
        "category": "Serums",
        "price": 1120,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-VTReedleResized.png?v=1763678822",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-101",
        "name": "VT COSMETICS - VT Reti-A Reedle Shot 100",
        "brand": "VT COSMETICS",
        "category": "Serums",
        "price": 1120,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/Soko-Glam-PDP-VTReedleResized-6.png?v=1763678807",
        "description": "A concentrated serum step for targeted care. It fits between toner and moisturizer in the routine.",
        "details": "This product targets a specific routine need. Serums are important because they show product variety and skincare knowledge. Brand: VT COSMETICS. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-102",
        "name": "Live Tinted - Hueguard® Glotion Mineral Sunscreen Broad Spectrum SPF 50",
        "brand": "Live Tinted",
        "category": "Sun Care",
        "price": 1260,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/sku_f0264_shades_light-medium_01_Resized.jpg?v=1762834103",
        "description": "A daily sun care option for morning routines. It supports protection while keeping the skincare routine simple.",
        "details": "This product belongs to the daytime routine. It is important because sun care is a common daily skincare need. Brand: Live Tinted. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-103",
        "name": "Biodance - Rejuvenating Caviar PDRN Real Deep Mask",
        "brand": "Biodance",
        "category": "Masks",
        "price": 665,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/PDRN___250702_3D.png__Resized.jpg?v=1762156019",
        "description": "A focused mask step for special care days. It adds a spa-like moment to the skincare routine.",
        "details": "This product is used for extra care. Masks make the catalogue richer because customers often buy them for weekly routines. Brand: Biodance. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    },
    {
        "id": "gc-104",
        "name": "SOKO GLAM - 5-Step Anti-Aging Set",
        "brand": "SOKO GLAM",
        "category": "Sets",
        "price": 3325,
        "image": "https://cdn.shopify.com/s/files/1/0249/1218/files/5-STEPANTI-AGINGSET_1.png?v=1776399263",
        "description": "A curated set that brings several beauty steps together. It is useful for gifting or trying a complete routine.",
        "details": "This product is useful because it combines more than one routine step. Sets also make the store look more realistic and gift-friendly. Brand: SOKO GLAM. Source catalogue: Soko Glam.",
        "source": "Soko Glam"
    }
];
